### ISSUE TITLE
Uncaught TypeError: Cannot call method 'getSelection' of undefined 

### ISSUE THREAD

**Issue by lmartins** [Azeirah/quippet#2]
After updating the plugin, which also changed the keyword assigned to the new snippet command, it now returns an error when opening the new snippet dialog:
https://www.dropbox.com/s/hfay001339qfw5s/Screenshot%202014-07-01%2022.56.26.png

**Comment by Azeirah** [comment]
Ah, good find. My code assumes that you have an editor open for the automatic selection paste. This had nothing to do with the update by the way.

Thanks for the bug reports so far.

I'll added a check to see if an editor pane exists.

**Comment by lmartins** [comment]
Thank you @Azeirah for the updates.
